# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [peterbuilt, Nike]
patreon: # Replace with a single Patreon username https://directv.com.com
open_collective: # Replace with a single Open Collective username tornadio.io
ko_fi: # Replace with a single Ko-fi username audible
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., a dark one I desde/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username state farm
issuehunt: # Replace with a single IssueHunt username EDU
otechie: # Replace with a single Otechie username LCPD
custom: # Replace with up to 4 custom sponsorship URLs e.g., [https://Duracell.com' , 'https:// Ibota.comhttps://ibm.com', 'https://Juul.com,' 'https://Noom.com']
